yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path(
        'author/', views.AuthorPage.as_view(), name='author'
    ),
    path(
        'tech/', views.TechPage.as_view(), name='tech'
    ),

]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('create/', views.post_create, name='post_create'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    # path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        "Название группы", max_length=200,
        help_text='Максимум 100 символов')
    slug = models.SlugField(
        "Краткое название группы",
        max_length=200, unique=True, help_text='Максимум 200 символов'
    )
    description = models.TextField("Описание",
                                   blank=True,
                                   null=True,
                                   help_text='Максимум 300 символов')

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name="текст",
                            help_text='основной текст поста', null=True)
    pub_date = models.DateTimeField(verbose_name="дата публикации",
                                    help_text='дата публикации поста',
                                    null=True, auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               verbose_name="автор",
                               help_text='имя автора поста',
                               related_name='posts', null=True)
    group = models.ForeignKey(Group, on_delete=models.SET_NULL,
                              verbose_name="группа",
                              help_text='название группы поста',
                              related_name='posts',
                              blank=True, null=True)

    def __str__(self):
        return self.text[:15]

    class Meta:
        ordering = ['-pub_date']

yatube/posts/forms.py
from .models import Post
from django import forms


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')
        labels = {
            'text': 'Текст',
            'group': 'Группа',
        }
        exclude = ('date', 'author')

    def clean_subject(self):
        data = self.cleaned_data['text']
        if data == '':
            raise forms.ValidationError('Вы должны что-то написать')
        return data

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Group
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from .forms import PostForm
from django.shortcuts import redirect
from .models import User
from django.conf import settings


# Главная страница
# @login_required


def index(request):
    post_list = Post.objects.select_related('author', 'group').all()
    paginator = Paginator(post_list, settings.TEN_SLICE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    template = 'posts/index.html'
    return render(request, template, context)


# Страница со сгруппированными постами
def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.select_related('author', 'group').all()
    paginator = Paginator(post_list, settings.TEN_SLICE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj
    }
    template = 'posts/group_list.html'
    return render(request, template, context)


def profile(request, username):
    author = User.objects.filter(username=username)[0]
    posts = author.posts.select_related('author', 'group').all()
    num_of_posts = posts.count()
    paginator = Paginator(posts, settings.TEN_SLICE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'author': author,
        'postsnum': num_of_posts,
        'page_obj': page_obj
    }
    return render(request, 'posts/profile.html', context)


@login_required
def post_create(request):
    groups = Group.objects.all()
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.author = request.user
            form.save()
            return redirect(f'/profile/{request.user.username}/')
        return render(request, 'posts/create_post.html', {'form': form})
    form = PostForm()
    return render(request, 'posts/create_post.html',
                  {'form': form, 'groups': groups})


def post_detail(request, post_id):
    post = Post.objects.select_related('author', 'group').filter(pk=post_id)[0]
    author = User.objects.filter(username=post.author)[0]
    num_of_posts = author.posts.select_related('author', 'group').all().count()
    title = post.text[:30]
    if request.user == author:
        is_author = True
    else:
        is_author = False
    context = {
        'post': post,
        'postsnum': num_of_posts,
        'title': title,
        'author': author,
        'is_author': is_author
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_edit(request, post_id):
    is_edit = True
    groups = Group.objects.all()
    post = Post.objects.select_related('author', 'group').filter(pk=post_id)[0]
    if post.author != request.user:
        return redirect(f'/posts/{post_id}/')
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect(f'/posts/{post_id}/')
        return render(request, 'posts/create_post.html',
                      {'form': form, 'groups': groups,
                       'id': post_id, 'post': post, 'is_edit': is_edit})
    form = PostForm()
    return render(request, 'posts/create_post.html',
                  {'form': form, 'groups': groups,
                   'post': post, 'is_edit': is_edit})

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
{% if is_edit %}
Редактирование поста
{% else %}
Новый пост
{% endif %}
{% endblock %}
{% block content %} 
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                {% if is_edit %}
                Редактировать запись
              {% else %}
                Добавить запись
              {% endif %}             
              </div>
              <div class="card-body">        
                {% if is_edit %}
                  <form method="post" action="{% url 'posts:post_edit' post.pk %}">
                {% else %}
                  <form method="post" action="{% url 'posts:post_create' %}">
              {% endif %}     
                  {% csrf_token %}       
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      {{ form.text.label }}                  
                      <span class="required text-danger" >*</span>                  
                    </label>
                    <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">{% if is_edit %}{{ post.text }}{% endif %}</textarea>                
                    <small id="id_text-help" class="form-text text-muted">
                    {{ form.text.help_text }}    
                    </small>                  
                  </div>            
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      {{ form.group.label }}              
                    </label> 
                    <select name="group" class="form-control" id="id_group">
                      <option value="" selected>---------</option>
                      {% for gr in groups %}
                        <option value={{ gr.pk }}>{{ gr }}</option>
                      {% endfor %}
                    </select>
                    <small id="id_group-help" class="form-text text-muted">
                      {{ form.group.help_text }}
                    </small>
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                      Сохранить
                    {% else %}
                      Добавить
                    {% endif %}      
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
Записи сообщества {{ group.title }}
{% endblock %}
{% block content %}
      <div class="container py-5">
        <h1>{{ group.title }}</h1>
        <p>
          {{ group.description }}
        </p>
        {% for post in page_obj %}
          <article>
            {% include 'includes/postcard.html' %}       
          </article>
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        {% include 'includes/paginator.html' %}
      </div>  
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
Последние обновления на сайте
{% endblock %}
{% block content %}
      <div class="container py-5">     
        <h1>{{ text }}</h1>
        {% for post in page_obj %}
          <article>
            {% include 'includes/postcard.html' %}
            {% if post.group %}  
              <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы {{ post.group }}</a>
            {% endif %}  
          </article>
            {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        {% include 'includes/paginator.html' %}
      </div>  
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}
Пост {{ title }}
{% endblock %}
{% block content %}
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date }}
            </li>
            <!-- если у поста есть группа -->   
            <li class="list-group-item">
              {% if post.group %}   
              <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
              {% endif %}   
            </li>
            <li class="list-group-item">
              Автор: {{ post.author}}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span> {{ postsnum }} </span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' author %}">
                все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          <p>
            {{ post.text }}
          </p>
             {% if is_author %}
             <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">
              редактировать запись
              {% endif %}    
            </a>     
        </article>
      </div> 
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
Профайл пользователя {{ author.username }}
{% endblock %}
{% block content %}
      <div class="container py-5">        
        <h1>Все посты пользователя {{ author.username }}</h1>
        <h3>Всего постов: {{ postsnum }} </h3>   
        {% for post in page_obj %}
        <article>
          <ul>
            <li>
              Автор: {{ author }}
              <a href="">все посты пользователя</a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date }} 
            </li>
          </ul>
          <p>
            {{ post.text }}
          </p>
          <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
        </article>       
        {% if post.group %}   
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}     
        <hr>
        <!-- Остальные посты. после последнего нет черты -->
        <!-- Здесь подключён паджинатор -->  
        {% endfor %}
      </div>
      {% include 'includes/paginator.html' %}
    {% endblock %}